#!/usr/bin/env -S bash -e

PROJECT=$1
RELEASE_VERSION=$2
VERSION_FAMILY=$3
WORKSPACE=${WORKSPACE:-'.'}

if [ -z "$PROJECT" ]; then
	echo "ERROR: Project not supplied"
	exit 1
fi
if [ -z "$RELEASE_VERSION" ]; then
	echo "ERROR: Release version argument not supplied"
	exit 1
fi
if [ -z "$VERSION_FAMILY" ]; then
	echo "ERROR: Version family argument not supplied"
	exit 1
fi

pushd ${WORKSPACE}

DIST=distribution/target/dist/hibernate-$PROJECT-$RELEASE_VERSION-dist.zip
if [ ! -f $DIST ]; then
	# Legacy layout; see upload-distribution.sh
	DIST=distribution/target/hibernate-$PROJECT-$RELEASE_VERSION-dist.zip
fi
unzip $DIST -d distribution/target/unpacked
DOCUMENTATION_DIRECTORY=$(readlink -e "distribution/target/unpacked/hibernate-${PROJECT}-${RELEASE_VERSION}/docs")

# Add various metadata to the header

if [ "$PROJECT" == "validator" ]; then
	META_DESCRIPTION="Hibernate Validator, Annotation based constraints for your domain model - Reference Documentation"
	META_KEYWORDS="hibernate, validator, hibernate validator, validation, bean validation"
elif [ "$PROJECT" == "ogm" ]; then
	META_DESCRIPTION="Hibernate OGM, JPA for NoSQL datastores - Reference Documentation"
	META_KEYWORDS="hibernate, ogm, hibernate ogm, nosql, jpa, infinispan, mongodb, neo4j, cassandra, couchdb, ehcache, redis"
elif [ "$PROJECT" == "search" ]; then
	META_DESCRIPTION="Hibernate Search, full text search for your entities - Reference Documentation"
	META_KEYWORDS="hibernate, search, hibernate search, full text, lucene, elasticsearch"
else
	META_DESCRIPTION=""
	META_KEYWORDS=""
fi

for file in $(find ${DOCUMENTATION_DIRECTORY}/reference/ -name \*.html); do
	# Only add the information if the file is generated by Docbook (the Asciidoctor output already has these information)
	if grep -q '<meta name="generator" content="DocBook ' ${file}; then
		# Add the metadata to the header
		sed -i 's@</title><link rel="stylesheet"@</title><!-- HibernateDoc.Meta --><meta name="description" content="'"$META_DESCRIPTION"'" /><meta name="keywords" content="'"$META_KEYWORDS"'" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><link rel="canonical" href="https://docs.jboss.org/hibernate/stable/'"$PROJECT"'/reference/en-US/html_single/" /><!-- /HibernateDoc.Meta --><link rel="stylesheet"@' ${file}

		# Add the outdated content Javascript at the bottom of the pages
		sed -i 's@</body>@<!-- HibernateDoc.OutdatedContent --><script src="//code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script><script src="/hibernate/_outdated-content/outdated-content.js" type="text/javascript"></script><script type="text/javascript">var jQuery_3_1 = $.noConflict(true); jQuery_3_1(document).ready(function() { HibernateDoc.OutdatedContent.install("'"$PROJECT"'"); });</script><!-- /HibernateDoc.OutdatedContent --></body>@' ${file}
	fi
done

# Clone git repo for docs.hibernate.org
DOCS_HIBERNATE_ORG_CLONE=$(mktemp -d --tmpdir 'docs-hibernate-org-XXXXXXXXXX')
# Make sure to clean up when the script exits
trap "rm -rf '${DOCS_HIBERNATE_ORG_CLONE}'" EXIT
pushd "${DOCS_HIBERNATE_ORG_CLONE}"
# Use a sparse checkout because the working dir can be huge (more than 6 GB)
# while .git data is relatively small (about 300 MB)
git clone --sparse --depth 1 git@github.com:hibernate/docs.hibernate.org.git .
DOCS_RELEASE_DIR="${PROJECT}/${VERSION_FAMILY}"
git sparse-checkout set "/stable" "/${DOCS_RELEASE_DIR}" "/_outdated-content"

# Set up commit info
git config user.name "Hibernate CI"
git config user.email "ci@hibernate.org"

# Copy documentation to the git repo for docs.hibernate.org
rsync -av \
	--delete \
	"${DOCUMENTATION_DIRECTORY}/" "${DOCS_RELEASE_DIR}"
git add -A . && git commit -m "Documentation for ${PROJECT} ${VERSION_FAMILY}"

# If the release is the new stable one, we need to update the doc server (outdated content descriptor and /stable/ symlink)

function version_gt() {
	test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1";
}

if [[ $RELEASE_VERSION =~ .*\.Final ]]; then
	JSON_INFO=_outdated-content/${PROJECT}.json
	if [ ! -s ${JSON_INFO} ]; then
		echo "Cannot find the ${JSON_INFO} descriptor. Exiting."
		exit 1
	fi
	CURRENT_STABLE_VERSION=$(cat "${JSON_INFO}" | jq -r ".stable")

	if [ "$CURRENT_STABLE_VERSION" != "$VERSION_FAMILY" ] && version_gt $VERSION_FAMILY $CURRENT_STABLE_VERSION; then
		# Update the JSON descriptor for use in javascript
		# See "Add the outdated content Javascript at the bottom of the pages" above
		JSON_INFO_UPDATED=_outdated-content/${PROJECT}-updated.json
		cat "${JSON_INFO}" | jq ".stable = \"$VERSION_FAMILY\"" > "${JSON_INFO_UPDATED}"
		if [ ! -s "${JSON_INFO_UPDATED}" ]; then
			echo "Error updating the ${JSON_INFO} descriptor. Exiting."
			exit 1
		fi
		mv "${JSON_INFO_UPDATED}" "${JSON_INFO}"

		# update the symlink of stable to the latest release
		pushd stable
		rm ${PROJECT}
		ln -s ../${PROJECT}/$VERSION_FAMILY ${PROJECT}
		popd

		git add -A . && git commit -m "Set the latest stable for ${PROJECT} to ${VERSION_FAMILY}"
	fi
fi

# Push
# We assume that:
# - SSH config allows relying on the SSH agent for github.com ("IdentitiesOnly no")
# - The SSH agent is already running with the appropriate SSH key already unlocked and available
git push origin HEAD:main

popd

popd
